apiVersion: apps/v1
kind: Deployment
metadata:
  name: singlegamepod-4
  namespace: default
  labels:
    podtype: singlegamepod-4
spec:
  replicas: 1
  selector:
    matchLabels:
      podtype: singlegamepod-4

  template:

    metadata:
      labels:
        podtype: singlegamepod-4

    spec:
      containers:
        - name: singlegamepod-4
          image: gcr.io/cheaper-324003/singlegame:latest

          ports:
            - containerPort: 80

          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 2
            httpGet:
              path: /health
              port: 80
          
          livenessProbe:
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 2
            httpGet:
              path: /health
              port: 80

---

apiVersion: v1
kind: Service
metadata:
  name: singlegamepod-4
spec:
  type: NodePort
  selector:
    podtype: singlegamepod-4
  ports:
    - port: 80
      targetPort: 80


# ---
# apiVersion: cloud.google.com/v1beta1
# kind: BackendConfig
# metadata:
#   name: openstream-backend-config
# spec:
#   sessionAffinity:
#     affinityType: "CLIENT_IP"
#   timeoutSec: 300
#   connectionDraining:
#     drainingTimeoutSec: 600

    