apiVersion: apps/v1
kind: Deployment
metadata:
  name: multigamepod-d
  namespace: default
  labels:
    podtype: multigamepod-d
spec:
  replicas: 1
  selector:
    matchLabels:
      podtype: multigamepod-d

  template:

    metadata:
      labels:
        podtype: multigamepod-d

    spec:
      containers:
        - name: multigamepod-d
          image: gcr.io/cheaper-324003/multi-game-pod:latest

          ports:
            - containerPort: 8000

          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 2
            httpGet:
              path: /
              port: 8000
          
          livenessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 2
            httpGet:
              path: /
              port: 8000

---

apiVersion: v1
kind: Service
metadata:
  name: multigamepod-api
spec:
  type: NodePort
  selector:
    podtype: multigamepod-d
  ports:
    - port: 8000
      targetPort: 8000

---

apiVersion: v1
kind: Service
metadata:
  name: multigamepod-websocket
spec:
  type: LoadBalancer
  selector:
    podtype: multigamepod-d
  ports:
    - port: 9000
      protocol: TCP
      targetPort: 9000

# ---
# apiVersion: cloud.google.com/v1beta1
# kind: BackendConfig
# metadata:
#   name: openstream-backend-config
# spec:
#   sessionAffinity:
#     affinityType: "CLIENT_IP"
#   timeoutSec: 300
#   connectionDraining:
#     drainingTimeoutSec: 600

    